In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
print(np.__version__)

1.26.4


In [7]:
# Create a NumPy ndarray Object
print(type(arr))

# Da bismo kreirali ndarray, mozemo da prosledimo f-ji listu, tuple, ili bilo koji objekat nalik nizu array() metodi

# Tuple pretvaramo u niz
arr = np.array((1, 2, 3, 4, 5))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
# Dimenzije nizova
# 0-D 
arr = np.array(42)
print(arr)

# 1-D
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# 3-D
arr = np.array([[[1,2,3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# Proveri broj dimenzija - ndim
a = np.array([[[1, 2, 3], [4, 5 ,6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)

3


In [16]:
# Kreiraj niz sa odredjenim brojem dimenzija
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [20]:
# Indeksiranje
# Pristup elementima niza

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
# Dodaj 3. i 4. element i saberi ih
print(arr[2] + arr[3])

1
2
7


In [25]:
# Pristup elementima 2-D niza
arr = np.array([[1,2,3], [4,5,6]])
print(arr[1,2])


6


In [29]:
# Pristup elementima 3-D niza
arr = np.array([[[1, 2, 3] , [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,2])

12


In [32]:
# Negativno indeksiranje
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, -2])

4


In [33]:
# Slicing arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [34]:
print(arr[4:])

[5 6 7]


In [36]:
print(arr[:4])

[1 2 3 4]


In [37]:
# Negative slicing
print(arr[-3:-1])

[5 6]


In [38]:
# Step
print(arr[1:5:2])

[2 4]


In [39]:
# Vrati svaki drugi element iz niza
print(arr[::2])

[1 3 5 7]


In [43]:
# Slicing 2-D arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 1:3])

[5 6]


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [50]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [51]:
# Data Type of an Array
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [54]:
arr = np.array(['aaa', 'dcvfghb', 'cd'])
print(arr.dtype)

<U7


In [55]:
# Kreiranje niza sa definisanim tipom podatka
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [57]:
# Definisanje velicine za i,u,f,S,U
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [58]:
# Value error
arr = np.array(['a', '2', '3'], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [59]:
# Konvertovanje tipa podatka u postojecem nizu
arr = np.array([1.1, 1.2, 1.3])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 1 1]
int32


In [60]:
arr = np.array([1.1, 1.2, 1.3])
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 1 1]
int64


In [64]:
arr = np.array([1, 1, 1])
newarr = arr.astype('bool')
print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


In [65]:
# Copy vs View
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [66]:
# View
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [67]:
# Make changes in the view
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [68]:
# base -> None | niz
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [72]:
# Shape
arr = np.array([[1,2,3,4], [5,6,7, 8]])
print(arr.shape)

(2, 4)


In [73]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [74]:
# Reshaping arrays
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
# from 1-D to 3-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [79]:
# Error
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(6,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [80]:
# Povratna vrednost
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2, 6).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
# Unknown dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [86]:
# Flattening the arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
newarr = arr.reshape(-1)
print((arr.reshape(-1)).base) #view
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [87]:
# Iterating through arrays
# 1-D
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [90]:
# 2-D
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [92]:
# da vratimo skalarne vrednosti
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [94]:
# 3-D
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

for x in arr:
    print(x)

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [98]:
# Iteracije koriscenjem nditer() funkcije
arr = np.array([[[1,2], [3,4]], [[5,6], [6,7]]])
print(arr)

arr.shape

for x in np.nditer(arr):
    print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
1
2
3
4
5
6
6
7


In [100]:
# Iteracija sa razlicitom velicinom koraka
arr = np.array([[1,2,3,4], [5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [101]:
# Enumerisana iteracija
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [102]:
arr = np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [103]:
# Join NumPy Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [105]:
# 2-D
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1)
print(arr2)

arr = np.concatenate((arr1, arr2), axis = 1) # spoji prve redove iz oba niza

print(arr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [110]:
# Joining arrays Using Stack Functions
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis = 1)

print(arr)
print(arr.shape)

# ne razumem? 

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [111]:
# Stacking along rows
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [112]:
# Stacking along columns
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [113]:
# Stacking along depth
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [3]:
# Split NumPy array

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [6]:
# Split 2-D arrays
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [9]:
# Split 2-D array along the row
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12],[13,14,15],[16,17,18]])

newarr = np.array_split(arr, 3, axis = 1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [13]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12],[13,14,15],[16,17,18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [17]:
# Search NumPy array
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

y = np.where(arr % 2 == 0)
print(y)

z = np.where(arr % 2 != 0)
print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


In [21]:
# Searched sorted
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, 7)

print(x)

# right most side
y = np.searchsorted(arr, 7, side = 'right')

print(y)

# Multiple values
z = np.searchsorted(arr, [2,4,6])

print(z)

3
4
[1 2 3]


In [26]:
# Sort NumPy Array

arr = np.array([3,2,0,1])
print((np.sort(arr)).base)

arr1 = np.array(['banana', 'apple', 'cherry'])
print(np.sort(arr1))

arr2 = np.array([True, False, True])
print(np.sort(arr2))

# Sorting 2-D arrays
arr3 = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr3))

None
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [27]:
# Filter NumPy Arrays
arr = np.array([41,42,43,44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [28]:
# Creating the filter array

arr = np.array([41,42,43,44])

filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(newarr)

[43 44]


In [29]:
# Filter array that returns only even numbers

arr = np.array([1,3,4,5,6,7,9])

filter_arr = []

for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(newarr)

[4 6]


In [4]:
# Create filter directly from array
arr = np.array([1,3,4,5,6,7,8,9])

filter_arr = arr > 6

newarr = arr[filter_arr]

print(newarr)

filter_arr1 = arr % 2 == 0

newarr1 = arr[filter_arr1]

print(newarr1)

[7 8 9]
[4 6 8]
